site_name: Tech

theme:
  name: material
  logo: assets/image/favicon.png
  favicon: assets/image/favicon.png
  icon:
    admonition:
      note: material/note-edit
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: amber
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Ubuntu
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - Home: index.md
  - tech:
      - Tailwindcss:
          - index: tailwindcss/index.md
          - forms: tailwindcss/forms.md

copyright: Copyright &copy; 2022 Arun kumar N
extra:
  generator: false
